// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Reception.Server.Auth.Repository;

#nullable disable

namespace Reception.Server.Auth.Migrations
{
    [DbContext(typeof(AuthContext))]
    [Migration("20240629232010_FixTokenEntityConfiguration")]
    partial class FixTokenEntityConfiguration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.8");

            modelBuilder.Entity("Reception.Server.Auth.Entities.Token", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("UserId");

                    b.ToTable("Token", "Auth");
                });

            modelBuilder.Entity("Reception.Server.Auth.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("FirstName")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .HasColumnType("TEXT");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MiddleName")
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasAlternateKey("Login")
                        .HasName("IX_Login");

                    b.ToTable("User", "Auth");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Login = "admin",
                            Password = "10000.Vu2dFkd1t3QvtvaXZm56zg==.dcrZ8CkHtpEg9rSYRu7/FNJUHDxuGeiU+4LD1vfPUg4="
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
