//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Reception.App.Localization.Languages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Language {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Language() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Reception.App.Localization.Languages.Language", typeof(Language).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auth checking. Please, wait...
        /// </summary>
        internal static string AuthChecking {
            get {
                return ResourceManager.GetString("AuthChecking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading auth data.
        /// </summary>
        internal static string AuthLoadData {
            get {
                return ResourceManager.GetString("AuthLoadData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LOG IN.
        /// </summary>
        internal static string AuthLogin {
            get {
                return ResourceManager.GetString("AuthLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string AuthPassword {
            get {
                return ResourceManager.GetString("AuthPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome.
        /// </summary>
        internal static string AuthTitle {
            get {
                return ResourceManager.GetString("AuthTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        internal static string AuthUsername {
            get {
                return ResourceManager.GetString("AuthUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ALLOW.
        /// </summary>
        internal static string BossAllow {
            get {
                return ResourceManager.GetString("BossAllow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DENY.
        /// </summary>
        internal static string BossDeny {
            get {
                return ResourceManager.GetString("BossDeny", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading boss data.
        /// </summary>
        internal static string BossLoadData {
            get {
                return ResourceManager.GetString("BossLoadData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WAIT.
        /// </summary>
        internal static string BossWait {
            get {
                return ResourceManager.GetString("BossWait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection status:.
        /// </summary>
        internal static string MainConnectionStatus {
            get {
                return ResourceManager.GetString("MainConnectionStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading...
        /// </summary>
        internal static string MainLoading {
            get {
                return ResourceManager.GetString("MainLoading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server status:.
        /// </summary>
        internal static string MainServerStatus {
            get {
                return ResourceManager.GetString("MainServerStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string MainSettingsTooltip {
            get {
                return ResourceManager.GetString("MainSettingsTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Boss mode.
        /// </summary>
        internal static string SettingsBossMode {
            get {
                return ResourceManager.GetString("SettingsBossMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CANCEL.
        /// </summary>
        internal static string SettingsCancel {
            get {
                return ResourceManager.GetString("SettingsCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark theme.
        /// </summary>
        internal static string SettingsDarkTheme {
            get {
                return ResourceManager.GetString("SettingsDarkTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        internal static string SettingsLanguage {
            get {
                return ResourceManager.GetString("SettingsLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SAVE.
        /// </summary>
        internal static string SettingsSave {
            get {
                return ResourceManager.GetString("SettingsSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System theme.
        /// </summary>
        internal static string SettingsSystemTheme {
            get {
                return ResourceManager.GetString("SettingsSystemTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string SettingsTitle {
            get {
                return ResourceManager.GetString("SettingsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect to chat hub...
        /// </summary>
        internal static string SubordinateConnectToChat {
            get {
                return ResourceManager.GetString("SubordinateConnectToChat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First name.
        /// </summary>
        internal static string SubordinateFirstName {
            get {
                return ResourceManager.GetString("SubordinateFirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading subordinate data.
        /// </summary>
        internal static string SubordinateLoadData {
            get {
                return ResourceManager.GetString("SubordinateLoadData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load photo...
        /// </summary>
        internal static string SubordinateLoadPhoto {
            get {
                return ResourceManager.GetString("SubordinateLoadPhoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message.
        /// </summary>
        internal static string SubordinateMessage {
            get {
                return ResourceManager.GetString("SubordinateMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Middle name.
        /// </summary>
        internal static string SubordinateMiddleName {
            get {
                return ResourceManager.GetString("SubordinateMiddleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Post.
        /// </summary>
        internal static string SubordinatePost {
            get {
                return ResourceManager.GetString("SubordinatePost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        internal static string SubordinateSearch {
            get {
                return ResourceManager.GetString("SubordinateSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Searching...
        /// </summary>
        internal static string SubordinateSearching {
            get {
                return ResourceManager.GetString("SubordinateSearching", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Second name.
        /// </summary>
        internal static string SubordinateSecondName {
            get {
                return ResourceManager.GetString("SubordinateSecondName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send.
        /// </summary>
        internal static string SubordinateSend {
            get {
                return ResourceManager.GetString("SubordinateSend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visitor on the way...
        /// </summary>
        internal static string SubordinateSendVisitor {
            get {
                return ResourceManager.GetString("SubordinateSendVisitor", resourceCulture);
            }
        }
    }
}
