<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.SignalR.Client" Version="10.0.5" />
    <PackageReference Include="Microsoft.AspNetCore.SignalR.Protocols.NewtonsoftJson" Version="10.0.5" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
    <PackageReference Include="RestSharp" Version="114.0.0" />
    <PackageReference Include="Splat" Version="19.3.1" />
    <PackageReference Include="System.Configuration.ConfigurationManager" Version="10.0.5" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Reception.App.Model\Reception.App.Model.csproj" />
    <ProjectReference Include="..\Reception.App.Service\Reception.App.Service.csproj" />
    <ProjectReference Include="..\Reception.Constant\Reception.Constant.csproj" />
    <ProjectReference Include="..\Reception.Model.Interfaces\Reception.Model.Interface.csproj" />
    <ProjectReference Include="..\Reception.Model.Network\Reception.Model.Network.csproj" />
  </ItemGroup>

</Project>
